name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main  # replace with your main branch name
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Build and Deploy
      env:
        JEKYLL_ENV: production
      run: |
        bundle install
        bundle exec jekyll build
        git config --global user.name "dpzkf"
        git config --global user.email "dpzkfzzz@gmail.com"
        cd _site
        git init
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force --quiet "https://${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" master:gh-pages
